### ISSUE TITLE
src/nvtt/icbc.cpp compilation errors

### ISSUE THREAD

**Issue by r-a-sattarov** [castano/nvidia-texture-tools#313] opened 2020-04-26 11:38 UTC
I get errors when compiling this file. I am compiling in Debian 10 with gcc 8.3.0 compiler.

CMake-configuration log:
- [cmake-config.txt](https://github.com/castano/nvidia-texture-tools/files/4535207/cmake-config.txt)

Сompilation log:
- [compile.txt](https://github.com/castano/nvidia-texture-tools/files/4535210/compile.txt)

Сompilation errors log:
- [compile_err.txt](https://github.com/castano/nvidia-texture-tools/files/4535211/compile_err.txt)

**Comment by castano** [comment] 2020-04-26 16:41
Was this issue fixed with #314?

**Comment by r-a-sattarov** [comment] 2020-04-26 18:34
> Was this issue fixed with #314?

Unfortunately, nope.

**Comment by akb825** [comment] 2020-05-10 03:49
The problem is it's #including the SSE intrinsic headers inside of a namespace. All #includes should be in the global namespace.

**Comment by akb825** [comment] 2020-05-10 21:46
I have a fix up with PR #316.

**Comment by r-a-sattarov** [comment] 2020-05-11 09:22
> I have a fix up with PR #316.

Yes, with these changes, compilation is possible. Thanks!

**Comment by castano** [comment] 2020-06-23 01:44
This should be fixed now.

**Closed by castano** 2020-06-23 01:44 UTC
